import AuthProvider from "@/lib/providers/Auth";
import WagmiProvider from "@/lib/providers/Wagmi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body>
        <WagmiProvider>
          <AuthProvider>{children}</AuthProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
