import AuthProvider from "@/lib/providers/Auth";
import DAppProvider from "@/lib/providers/Dapp";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body>
        <DAppProvider>
          <AuthProvider>{children}</AuthProvider>
        </DAppProvider>
      </body>
    </html>
  );
}
